version: "3.8"

services:
  application-db:
    container_name: application-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lappis
      - MONGO_INITDB_ROOT_PASSWORD=lappis
      - MONGO_INITDB_DATABASE=lappis
    volumes:
      - /mongodb/database:/data/db
    ports:
      - 27017:27017

  app-library:
    container_name: app-library
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - application-db

  metabase:
    ports:
      - 3000:3000
    image: metabase/metabase:latest
    volumes:
      - /data/:/metabase
    restart: always