version: "3.8"

services:
  application-db:
    container_name: application-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lappis
      - MONGO_INITDB_ROOT_PASSWORD=lappis
      - MONGO_INITDB_DATABASE=lappis
    volumes:
      - /mongodb/database:/data/db
    ports:
      - 27017:27017