name: CI GCES

on:
  push:
    branches:
      - 'main'

stages:
  - build
  - test

jobs:
  build:
    stage: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Executar containers
        run: |
          docker-compose up -d --build
          docker-compose logs

  test:
    stage: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - name: Instalar dependências 
        run: | 
          python -m pip install --upgrade pip 
          pip install pytest 
      - name: Executar testes
        run: pytest tests/


